- name: variables
  hosts: web
  vars:
    Emp: "Mamatha"
    city: "Hyderabad"
     
  tasks: 
   - name: variables
     ansible.builtin.debug:
      msg: "{ Emp name is {{ Emp }} city is {{ city }} }"
