- name: variables
  hosts: web
  vars:
    Emp: "Mamatha"
    city: "Hyderabad"
  vars_prompt:
    - name: Application
      prompt: please enter the course
  tasks: 
   - name: variables
     ansible.builtin.debug:
      msg: "{ Emp name is {{ Emp }} city is {{ city }} {{Application}}  }"
