- name: vpc creation 
  hosts: localhost
  connection: local
  vars:
    vpc_name: iib-test-1
    cidr: 10.0.0.0/16
    region: us-east-1
  
  tasks:
  - name: crearte vpc
    amazon.aws.ec2_vpc_net:
     name: "{{vpc_name}}"
     cidr: "{{cidr}}"
     region: "{{region}}"
     dns_hostnames: true
     dns_support: true
     state: present
    register: output
  - name: display the vpc info of vpc
    debug:
      var: output.vpc.id